import json
import matplotlib.pyplot as plt


class TradeAnalyzer:
    """Graph data generated by logging bot

    See the txt file for the file format

    :param file: file path to be read from
    :type file: string
    """
    def __init__(self, file):
        self.data = self.parse_file(file)
        self.__x_axis = []
        self.__y_axis = []
        self.plt = plt

    @staticmethod
    def parse_file(file):
        """Load the file into memory

        :param file: file path
        :type file: string
        :return: json object
        :rtype: dict
        """
        with open(file, 'r') as fp:
            return json.load(fp)

    def draw(self, second_interval):
        """Draw the graph

        :param second_interval: second endpoint in x axis
        :type second_interval: float
        :return:
        """
        start_time = self.data[0]['T']
        for data in self.data:
            seconds = (data['T'] - start_time)
            self.__x_axis.append(data['T'] - start_time)
            self.__y_axis.append(float(data['p']))
            if seconds >= second_interval:
                break
        self.plt.plot(self.__x_axis, self.__y_axis)
        self.plt.xlabel("miliseconds")
        self.plt.ylabel("price")

    def save_graph(self, path):
        """Save the graph to file

        :param path: path of the file to be saved
        :type path: string
        :return:
        """
        self.plt.savefig(path)

    def show(self):
        """Show the graph

        :return:
        """
        self.plt.show()
